#!/bin/sh

echo "Initializing LCD..."

echo 0 > /sys/class/gpio/gpio7/value

sleep .05
echo  '\x03' >> /dev/LCD_device
sleep .05
echo  '\x03' >> /dev/LCD_device
sleep .05
echo  '\x03' >> /dev/LCD_device
sleep .05
echo  '\x02' >> /dev/LCD_device
sleep .05
echo  '\x0C' >> /dev/LCD_device
sleep .05
echo  '\x01' >> /dev/LCD_device
sleep .05
echo  '\x06' >> /dev/LCD_device
sleep .05
echo  '\x28' >> /dev/LCD_device
sleep .05

echo "Done!"

echo 1 > /sys/class/gpio/gpio7/value